---
- name: create directory structure for technitium
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ install_directory }}"

- name: create docker-compose file to run container
  template:
    src: docker-compose.yml.j2
    dest: "{{ install_directory }}/docker-compose.yml"
    mode: 0655
  vars:
    configurations: "{{ dns_configurations }}"

- name: start container using docker-compose
  ansible.builtin.docker_compose:
    project_src: "{{ install_directory }}"
    state: present
    restarted: yes 

